import { UserModel } from "../../user/user.model";

/**
 * Represent sign in response data
 */
export interface SignInResponseData {
  /**
   * Authorization token generated by API
   */
  token: string;

  /**
   * Authenticated user
   */
  user: UserModel;
}
