name: Build and test backend and frontend for features and fixes branches

on:
  push:
    branches:
    - feature/**
    - fix/**

    paths:
    - ScienceArchive.Server/**

jobs:
  build-and-test-backend:
    name: Build and test backend solution
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 7.0.x

    - name: Restore dependenices
      working-directory: ScienceArchive.Server/
      run: dotnet restore

    - name: Build solution
      working-directory: ScienceArchive.Server/
      run: dotnet build --configuration Release --no-restore

    - name: Run tests
      working-directory: ScienceArchive.Server/
      run: dotnet test

