name: Backend deployment workflow from main branch

on:
  push:
    tags:
    - v**

    paths:
    - ScienceArchive.Server/**

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 7.0.x

    - name: Restore dependenices
      working-directory: ScienceArchive.Server/
      run: dotnet restore

    - name: Build solution
      working-directory: ScienceArchive.Server/
      run: dotnet build --configuration Release --no-restore

    - name: Run tests
      working-directory: ScienceArchive.Server/
      run: dotnet test


  deploy-backend:
    name: Build and delpoy backend
    runs-on: self-hosted
    needs: build-and-test

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build backend image
      working-directory: ScienceArchive.Server/
      run: |
        docker build \
          --build-arg POSTGRESQL_CONNECTION_STRING="${{ secrets.POSTGRESQL_CONNECTION_STRING }}" \
          -t ${{ secrets.BACKEND_IMAGE_NAME }} .

    - name: Run backend container
      run: docker run --net="host" -d ${{ secrets.BACKEND_IMAGE_NAME }}
